export const ROUTES = {
  INDEX: "/",
  AUTH: {
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    REGISTER: "/register",
  },
  PATIENT: {
    DASHBOARD: "/patient/dashboard",
    TRIAGE: "/patient/triage",
    MATCHING: "/patient/matching",
    CHECKOUT: "/patient/checkout",
    PAYMENT_REGULAR: "/patient/payment-regular",
    PAYMENT_BPJS: "/patient/payment-bpjs",
    CHAT_ROOM: "/patient/chat-room",
    OVERTIME_MODAL: "/patient/overtime-modal",
    RATING: "/patient/rating",
    HISTORY: "/patient/history",
    ARTICLES: "/patient/articles",
    PROFILE: "/patient/profile",
    PRESCRIPTION: "/patient/prescription",
    REFERRAL: "/patient/referral",
    DOCTORS: "/patient/doctors",
    DOCTOR_DETAIL: "/patient/doctor-detail",
    ASSESSMENT_RESULT: "/patient/assessment-result",
    SESSION_SUMMARY: "/patient/session-summary",
    NOTIFICATIONS: "/patient/notifications",
    ARTICLE_DETAIL: "/patient/article-detail",
    VIDEO_CALL: "/patient/video-call",
    EDIT_PROFILE: "/patient/edit-profile",
  },
  PRACTITIONER: {
    REGISTER: "/practitioner/register",
    DASHBOARD: "/practitioner/dashboard",
    WAR_ROOM: "/practitioner/war-room",
    CHAT: "/practitioner/chat",
    DIAGNOSIS: "/practitioner/diagnosis",
    WITHDRAW: "/practitioner/withdraw",
    BANK_ACCOUNT: "/practitioner/bank-account",
    HISTORY: "/practitioner/history",
    PROFILE: "/practitioner/profile",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    VERIFICATION: "/admin/verification",
    LEDGER: "/admin/ledger",
    SETTINGS: "/admin/settings",
  },
} as const;
